### ISSUE TITLE
Error occurred in event handler on_message (extension Mod)

### ISSUE THREAD

**Issue by PythonCoderAS** [PythonCoderAS/PokestarBot#17]
```python
Traceback (most recent call last):
  File "/Users/<user>/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/Users/<user>/PycharmProjects/PokestarBot/bot_data/extensions/mod.py", line 359, in on_message
    if await self.bot.blacklisted(context.guild.id, *emojis):
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by PythonCoderAS** [comment]
New traceback: 
```python
Traceback (most recent call last):
  File "/Users/<user>/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/Users/<user>/PycharmProjects/PokestarBot/bot_data/extensions/mod.py", line 359, in on_message
    if not context.guild and emojis and await self.bot.blacklisted(context.guild.id, *emojis):
AttributeError: 'NoneType' object has no attribute 'id'
