### ISSUE TITLE
Error occurred in getting stats in Direct Messages

### ISSUE THREAD

**Issue by PythonCoderAS** [PythonCoderAS/PokestarBot#18]
```python
Traceback (most recent call last):
  File "/home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/stats.py", line 39, in command_stats
    guild_id = getattr(channel.guild, "id", 0)
AttributeError: 'DMChannel' object has no attribute 'guild'
```

**Comment by PythonCoderAS** [comment]
New error:
```python
Traceback (most recent call last):
  File "/Users/aoyansarkar/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/aoyansarkar/PycharmProjects/PokestarBot/bot_data/extensions/stats.py", line 68, in command_stats
    user = non_member_user = ctx.guild.get_member(int(user_id))
AttributeError: 'NoneType' object has no attribute 'get_member'
```
