### ISSUE TITLE
Exception with `%update list`

### ISSUE THREAD

**Issue by PythonCoderAS** [PythonCoderAS/PokestarBot#31]
```python
Traceback (most recent call last):
  File "/home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/updates.py", line 351, in list
    members.append(member.mention)
AttributeError: 'NoneType' object has no attribute 'mention'
```

**Comment by PythonCoderAS** [comment]
Still exists.

**Comment by PythonCoderAS** [comment]
New exception:
```python
Traceback (most recent call last):
  File "/home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/updates.py", line 368, in list
    members.append(member.mention)
AttributeError: 'NoneType' object has no attribute 'mention'
```
