### ISSUE TITLE
%bot_stats throws exception

### ISSUE THREAD

**Issue by PythonCoderAS** [PythonCoderAS/PokestarBot#42]
```python
Traceback (most recent call last):
  File "/home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/misc.py", line 159, in cmd_bot_stats
    users = len({member.id for member in (guild.members for guild in self.bot.guilds)})
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/misc.py", line 159, in <setcomp>
    users = len({member.id for member in (guild.members for guild in self.bot.guilds)})
AttributeError: 'list' object has no attribute 'id'
```

**Comment by PythonCoderAS** [comment]
Still persists
