### ISSUE TITLE
Exception on %issue

### ISSUE THREAD

**Issue by PythonCoderAS** [PythonCoderAS/PokestarBot#45]
```python
Traceback (most recent call last):
  File "/home/PokestarFan/.local/share/virtualenvs/PokestarBot-NMj7rRyG/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/PokestarFan/PokestarBot/bot_data/extensions/misc.py", line 189, in github_issue
    issue_number = await post_issue(self.bot.session, f"Issue Reported by {ctx.author}", body=description)
  File "/home/PokestarFan/PokestarBot/bot_data/utils/post_issue.py", line 19, in post_issue
    raise aiohttp.ClientResponseError(aiohttp.RequestInfo(request.url, request.method, request.headers, request.real_url), (request,),
aiohttp.client_exceptions.ClientResponseError: 400, message="{'message': 'Problems parsing JSON', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}", url=URL('https://api.github.com/repos/PythonCoderAS/PokestarBot/issues')
```

**Comment by PythonCoderAS** [comment]
```
a `b` c
```
